# Site settings
title: Christopher Steiner
email: chris AT chrissteiner DOT com
description: > # this means to ignore newlines until "baseurl:"
  Christopher Steiner is a founder, engineer, New York Times Bestselling Author, dad, husband and skier. 
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: steinerwriter
github_username:  Linkedin

# Build settings
markdown: kramdown
